name: cve-2019-9514
class: kubernetes
type: traffic_interception
dependencies:
  - name: kubectl
    version: 1.11.1
    versions: ~
  - name: kubelet
    version: 1.11.1
    versions: ~
  - name: kubeadm
    version: 1.11.1
    versions: ~
links:
  - https://nvd.nist.gov/vuln/detail/CVE-2019-9946
  - https://github.com/containernetworking/plugins/pull/269#issuecomment-477683272
  - http://blog.champtar.fr/CVE-2019-9946/
