name: cve-2019-5736
class: docker/runc
type: container_escape
dependencies:
  - name: docker-ce
    version: 17.03.0
    versions:
      - < 18.09.1
links:
  - https://nvd.nist.gov/vuln/detail/CVE-2019-5736
  - https://github.com/Frichetten/CVE-2019-5736-PoC
